version: 2.1
description: Android Tooling

executors:
  android:
    description: |
      Select a CircleCI convenience image to get building on Android.
      See https://hub.docker.com/r/circleci/android/tags for a full list of the available images.
    parameters:
      sdk:
        description: |
          The API level to use.
          For Android Oreo 8.1.0, use API level "27", for example.
          See https://source.android.com/setup/start/build-numbers for a full list.
        type: string
    docker:
      - image: circleci/android:api-<< parameters.sdk >>-alpha

commands:
  accept_licenses:
    steps:
      - run:
          name: Accept Android Licenses
          description: |
            Accepts all Android SDK licenses.
            This command is typically not necessary to execute, since the CircleCI convenience images
            ship with all licenses accepted.
            This command will add approximately 10 seconds to the build time.
          # Use a custom shell.
          # We don't `set -o pipefail` since sdkmanager does not interact nicely
          # with the incoming pipe, which can result in the `yes` command exiting with code 147.
          shell: /bin/bash -e
          command: |
            yes | sdkmanager --licenses
            yes | sdkmanager --update
  save_build_cache:
    description: |
      Save the Android build-cache.
          The build cache stores certain outputs that the Android plugin for Gradle
          generates when building your project (such as unpackaged AARs and pre-dexed
          remote dependencies). Your clean builds are much faster while using the
          cache because the build system can simply reuse those cached files during
          subsequent builds, instead of recreating them. The build cache also works
          on continuous integration servers and when running multiple build processes
          on a single local machine.

      See https://developer.android.com/studio/build/build-cache
    steps:
      - save_cache:
          key: android-orb-v1-{{ epoch }}
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
  restore_build_cache:
    description: Restore the build cache. See `save_build_cache` for more information.
    steps:
      - restore_cache:
          key: android-orb-v1-

jobs:
  build:
    executor:
      name: android
      sdk: "23"
    steps:
      - checkout
      - accept_licenses
