version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.5.0
  android: circleci/android@dev:alpha

jobs:
  android:
    parameters:
      tag:
        type: string
        description: circleci/android tag

      ndk-version:
        type: string
        description: ndk version to install

      ndk-sha:
        type: string
        description: ndk sha value to pass

      resource-class:
        type: enum
        enum: [small, medium, medium+, large, xlarge]
        default: small

    resource_class: <<parameters.resource-class>>
    docker:
      - image: circleci/android:<<parameters.tag>>

    steps:
      - checkout

      - android/install-ndk:
          ndk-version: <<parameters.ndk-version>>
          ndk-sha: <<parameters.ndk-sha>>

integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    17c-23-master,
    17c-24-master,
    17c-25-master,
    17c-26-master,
    17c-27-master,
    17c-28-master,
    17c-29-master,
    18b-23-master,
    18b-24-master,
    18b-25-master,
    18b-26-master,
    18b-27-master,
    18b-28-master,
    18b-29-master,
    19c-23-master,
    19c-24-master,
    19c-25-master,
    19c-26-master,
    19c-27-master,
    19c-28-master,
    19c-29-master
  ]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/android
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: 94:6f:77:19:c2:d9:0b:e0:fb:fe:d6:65:39:38:29:d3
          cleanup-tags: true
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          ssh-fingerprints: 94:6f:77:19:c2:d9:0b:e0:fb:fe:d6:65:39:38:29:d3
          cleanup-tags: true
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      # 17c
      - android:
          name: 17c-23-dev
          tag: api-23
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          resource-class: medium
          filters: *integration-dev_filters

      - android:
          name: 17c-24-dev
          tag: api-24
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          resource-class: medium
          filters: *integration-dev_filters

      - android:
          name: 17c-25-dev
          tag: api-25
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-dev_filters

      - android:
          name: 17c-26-dev
          tag: api-26
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-dev_filters

      - android:
          name: 17c-27-dev
          tag: api-27
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          resource-class: medium
          filters: *integration-dev_filters

      - android:
          name: 17c-28-dev
          tag: api-28
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-dev_filters

      - android:
          name: 17c-29-dev
          tag: api-29
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-dev_filters

      # 18b
      - android:
          name: 18b-23-dev
          tag: api-23
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-dev_filters

      - android:
          name: 18b-24-dev
          tag: api-24
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-dev_filters

      - android:
          name: 18b-25-dev
          tag: api-25
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-dev_filters

      - android:
          name: 18b-26-dev
          tag: api-26
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-dev_filters

      - android:
          name: 18b-27-dev
          tag: api-27
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          resource-class: medium
          filters: *integration-dev_filters

      - android:
          name: 18b-28-dev
          tag: api-28
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          resource-class: medium
          filters: *integration-dev_filters

      - android:
          name: 18b-29-dev
          tag: api-29
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-dev_filters

      # 19c
      - android:
          name: 19c-23-dev
          tag: api-23
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          resource-class: medium
          filters: *integration-dev_filters

      - android:
          name: 19c-24-dev
          tag: api-24
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-dev_filters

      - android:
          name: 19c-25-dev
          tag: api-25
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-dev_filters

      - android:
          name: 19c-26-dev
          tag: api-26
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          resource-class: medium
          filters: *integration-dev_filters

      - android:
          name: 19c-27-dev
          tag: api-27
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-dev_filters

      - android:
          name: 19c-28-dev
          tag: api-28
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-dev_filters

      - android:
          name: 19c-29-dev
          tag: api-29
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-dev_filters

      # triggered by master branch commits
      # 17c
      - android:
          name: 17c-23-master
          tag: api-23
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          resource-class: medium
          filters: *integration-master_filters

      - android:
          name: 17c-24-master
          tag: api-24
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          resource-class: medium
          filters: *integration-master_filters

      - android:
          name: 17c-25-master
          tag: api-25
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-master_filters

      - android:
          name: 17c-26-master
          tag: api-26
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-master_filters

      - android:
          name: 17c-27-master
          tag: api-27
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          resource-class: medium
          filters: *integration-master_filters

      - android:
          name: 17c-28-master
          tag: api-28
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-master_filters

      - android:
          name: 17c-29-master
          tag: api-29
          ndk-version: android-ndk-r17c
          ndk-sha: 12cacc70c3fd2f40574015631c00f41fb8a39048
          filters: *integration-master_filters

      # 18b
      - android:
          name: 18b-23-master
          tag: api-23
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-master_filters

      - android:
          name: 18b-24-master
          tag: api-24
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-master_filters

      - android:
          name: 18b-25-master
          tag: api-25
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-master_filters

      - android:
          name: 18b-26-master
          tag: api-26
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-master_filters

      - android:
          name: 18b-27-master
          tag: api-27
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          resource-class: medium
          filters: *integration-master_filters

      - android:
          name: 18b-28-master
          tag: api-28
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          resource-class: medium
          filters: *integration-master_filters

      - android:
          name: 18b-29-master
          tag: api-29
          ndk-version: android-ndk-r18b
          ndk-sha: 500679655da3a86aecf67007e8ab230ea9b4dd7b
          filters: *integration-master_filters

      # 19c
      - android:
          name: 19c-23-master
          tag: api-23
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          resource-class: medium
          filters: *integration-master_filters

      - android:
          name: 19c-24-master
          tag: api-24
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-master_filters

      - android:
          name: 19c-25-master
          tag: api-25
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-master_filters

      - android:
          name: 19c-26-master
          tag: api-26
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          resource-class: medium
          filters: *integration-master_filters

      - android:
          name: 19c-27-master
          tag: api-27
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-master_filters

      - android:
          name: 19c-28-master
          tag: api-28
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-master_filters

      - android:
          name: 19c-29-master
          tag: api-29
          ndk-version: android-ndk-r19c
          ndk-sha: fd94d0be6017c6acbd193eb95e09cf4b6f61b834
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/android
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/android
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/android
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
