description: >
  Start building an Android project on CircleCI

parameters:
  executor:
    description: Executor for the job
    type: executor

executor: << parameters.executor >>

steps:
  - checkout
  - accept-licenses
